-- CREATE TABLE UsersTable(user_id VARCHAR(100)PRIMARY KEY NOT NULL,
-- name VARCHAR(200) NOT NULL,
-- email VARCHAR(200) UNIQUE NOT NULL,contact VARCHAR (100) NOT NULL,
-- password VARCHAR(200)NOT NULL,role VARCHAR(10) 
-- DEFAULT 'User' NOT NULL,is_registered VARCHAR(10) DEFAULT '0')



CREATE TABLE ClientsTable(client_id VARCHAR(200)  NOT NULL,
name VARCHAR(200) NOT NULL,
email VARCHAR(200)  PRIMARY KEY NOT NULL,contact VARCHAR (100) NOT NULL,
password VARCHAR(200)NOT NULL,role VARCHAR(10)
DEFAULT 'client' NOT NULL,is_welcome VARCHAR(10) DEFAULT '0')