
POST http://localhost:5000/clients/register
Content-Type: application/json


{
    "name":"Jonathan",
    "email":"jonathanndambuki16@gmail.com",
    "contact":"0712345678",
    "password":"@Jonathan254"
}

###
POST http://localhost:5000/clients/login
Content-Type: application/json

{
    
    "email":"admin@gmail.com",
    "password":"@Admin254"
}


###

GET http://localhost:5000/clients


###

GET http://localhost:5000/clients/d651f21b-0be4-4351-bbec-a6f5a504809c


#getName


###
GET http://localhost:5000/clients/name/jonathanndambuki16@gmail.com




//parcels endpoints


###

POST http://localhost:5000/parcels/add
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJhMDQwMmI2OS00NTViLTQwMjAtYTA1ZS03Y2E4YTEzY2ZhYWIiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImNvbnRhY3QiOiIwNzEyMzQ1Njc4Iiwicm9sZSI6ImFkbWluIiwiaXNfd2VsY29tZSI6IjAiLCJpYXQiOjE2NjM1ODYwNzIsImV4cCI6MTY2NzE4NjA3Mn0.RZIW9D83B5xslVUr4JPNF88bUI3VtDLRCtIeH6RekW8



{
    "sender_details":"wambuijuddie065@gmail.com",
    "receiver_details":"jonathanndambuki16@gmail.com",
    "pick_up":"Nai",
    "destination":"Nakuru",
    "description":"Fragile",
    "weight":20,
    "price":200,
    "status":"Dispatched"
}

###

GET http://localhost:5000/parcels
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJhMDQwMmI2OS00NTViLTQwMjAtYTA1ZS03Y2E4YTEzY2ZhYWIiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImNvbnRhY3QiOiIwNzEyMzQ1Njc4Iiwicm9sZSI6ImFkbWluIiwiaXNfd2VsY29tZSI6IjAiLCJpYXQiOjE2NjM1ODYwNzIsImV4cCI6MTY2NzE4NjA3Mn0.RZIW9D83B5xslVUr4JPNF88bUI3VtDLRCtIeH6RekW8



###

GET http://localhost:5000/parcels/d886ec0f-06bc-42be-b8b1-7b0163a2f65d

###

PATCH http://localhost:5000/parcels/deliver/85c16a96-a70e-499f-aece-04f19e3b1929
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJhMDQwMmI2OS00NTViLTQwMjAtYTA1ZS03Y2E4YTEzY2ZhYWIiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImNvbnRhY3QiOiIwNzEyMzQ1Njc4Iiwicm9sZSI6ImFkbWluIiwiaXNfd2VsY29tZSI6IjAiLCJpYXQiOjE2NjM1ODYwNzIsImV4cCI6MTY2NzE4NjA3Mn0.RZIW9D83B5xslVUr4JPNF88bUI3VtDLRCtIeH6RekW8


{
    "status":"delivered" 
}


###
DELETE  http://localhost:5000/parcels/delete/85c16a96-a70e-499f-aece-04f19e3b1929
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJhMDQwMmI2OS00NTViLTQwMjAtYTA1ZS03Y2E4YTEzY2ZhYWIiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImNvbnRhY3QiOiIwNzEyMzQ1Njc4Iiwicm9sZSI6ImFkbWluIiwiaXNfd2VsY29tZSI6IjAiLCJpYXQiOjE2NjM1ODYwNzIsImV4cCI6MTY2NzE4NjA3Mn0.RZIW9D83B5xslVUr4JPNF88bUI3VtDLRCtIeH6RekW8



###

GET  http://localhost:5000/parcels/sender/wambuijuddie065@gmail.com 

###

GET  http://localhost:5000/parcels/receiver/wambuijuddie065@gmail.com
