
POST http://localhost:5000/clients/register
Content-Type: application/json


{
    "name":"juslydy",
    "email":"juslydyjulivia@gmail.com",
    "contact":"0712345678",
    "password":"@Juslydy254"
}

###
POST http://localhost:5000/clients/login
Content-Type: application/json

{
    
    "email":"user2@gmail.com",
    "password":"@User2254"
}


###

GET http://localhost:5000/clients


###

GET http://localhost:5000/clients/d651f21b-0be4-4351-bbec-a6f5a504809c


//parcels endpoints


###

POST http://localhost:5000/parcels/add
Content-Type: application/json

{
    "sender_details":"juslydyjulivia@gmail.com",
    "receiver_details":"judynackson@gmail.com",
    "pick_up":"Nyeri",
    "destination":"Nakuru",
    "description":"Fragile",
    "weight":20,
    "price":200,
    "status":"dispatched"
}

###

GET http://localhost:5000/parcels

###

GET http://localhost:5000/parcels/100

###

PATCH http://localhost:5000/parcels/deliver/5395c77d-2c66-47b3-b231-1e04ccba6787
Content-Type: application/json

{
    "status":"delivered"  
}


###
PATCH http://localhost:5000/parcels/delete/100


###

# GET  http://localhost:5000/parcels/sender  
